#!/bin/sh /etc/rc.common
##############################################################################
#                                                                            #
#    OpenWrtMiner:  Bitcoin Miner based in OpenWrt capable AP and Routers    #
#                        V 0.1.0 - 2013 / 11 / 16                            #
#                                                                            #
##############################################################################
#                                                                            #
#    Copyright 2013 Daniel San Miguel IoXoI < ioxoi /a/ downby /·/ net >     #
#                                                                            #
#    This file is part of OpenWrtMiner.                                      #
#                                                                            #
#    OpenWrtMiner is free software: you can redistribute it and/or modify it #
#    under the terms of the GNU General Public License as published by the   #
#    Free Software Foundation, either version 3 of the License, or (at your  #
#    option) any later version.                                              #
#                                                                            #
#    OpenWrtMiner is distributed in the hope that it will be useful, but     #
#    WITHOUT ANY WARRANTY; without even the implied warranty of              #
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU        #
#    General Public License for more details.                                #
#                                                                            #
#    You should have received a copy of the GNU General Public License along #
#    with OpenWrtMiner. If not, see http://www.gnu.org/licenses/.            #
#                                                                            #
#                                                                            #
##############################################################################

START=99
STOP=50

PROG=/usr/bin/bfgminer

. /etc/bfgminer.cfg

start_service() {

		procd_open_instance
		procd_set_param command "$PROG"
		procd_close_instance
		
}
start() {
	$PROG $ARGS 2>&1 >> /tmp/bfgminer.log &
	echo $! > /var/run/bfgminer.pid
	/bin/chmod 600 /tmp/bfgminer.log
}
stop() { 
	kill `cat /var/run/bfgminer.pid`

 }

status() {
	/usr/bin/bfgminer-rpc summary 127.0.0.1 4028
}
